"""add_recommendation_model

Revision ID: 62fcc39068ef
Revises: e79d0ed4e94f
Create Date: 2025-06-03 11:41:59.949318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62fcc39068ef'
down_revision: Union[str, None] = 'e79d0ed4e94f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
