"""add_action_taken_to_recommendation_action

Revision ID: 9367cd0b6089
Revises: ba140fcf9cd9
Create Date: 2025-06-03 11:52:17.594518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9367cd0b6089'
down_revision: Union[str, None] = 'ba140fcf9cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_actions', sa.Column('action_taken', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation_actions', 'action_taken')
    # ### end Alembic commands ###
