"""add_roles_and_admin_user

Revision ID: 957f7d0bafc0
Revises: f0f2877e5f0c
Create Date: 2025-06-03 15:33:58.374767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957f7d0bafc0'
down_revision: Union[str, None] = 'f0f2877e5f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
