"""add first_name last_name birthdate to student_profiles

Revision ID: 98a41ff6e3f9
Revises: 957f7d0bafc0
Create Date: 2025-06-03 17:28:57.772346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98a41ff6e3f9'
down_revision: Union[str, None] = '957f7d0bafc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('birthdate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'birthdate')
    op.drop_column('student_profiles', 'last_name')
    op.drop_column('student_profiles', 'first_name')
    # ### end Alembic commands ###
