"""add_student_recommendation_relationship

Revision ID: ba140fcf9cd9
Revises: 62fcc39068ef
Create Date: 2025-06-03 11:49:48.665394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba140fcf9cd9'
down_revision: Union[str, None] = '62fcc39068ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
