"""modularize models and add nudge tracking

Revision ID: e316bf0cc383
Revises: d29b9377a6d5
Create Date: 2025-05-31 18:31:55.208830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e316bf0cc383'
down_revision: Union[str, None] = 'd29b9377a6d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
