"""add recruiter_id to student_profiles

Revision ID: e53ddc119c5c
Revises: 98a41ff6e3f9
Create Date: 2025-06-03 17:35:30.357362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53ddc119c5c'
down_revision: Union[str, None] = '98a41ff6e3f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('recruiter_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'recruiter_id')
    # ### end Alembic commands ###
