"""add_action_date_to_recommendation_action

Revision ID: f0f2877e5f0c
Revises: 9367cd0b6089
Create Date: 2025-06-03 11:54:25.749087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f2877e5f0c'
down_revision: Union[str, None] = '9367cd0b6089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_actions', sa.Column('action_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation_actions', 'action_date')
    # ### end Alembic commands ###
